# Generated by Django 5.0.6 on 2024-06-10 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tobacco', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prepmethod',
            options={'verbose_name': 'Метод приготовления', 'verbose_name_plural': 'Методы приготовления'},
        ),
    ]
