# Generated by Django 5.0.6 on 2024-06-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('phone', models.CharField(max_length=120, verbose_name='Номер телефона')),
                ('work_time', models.CharField(max_length=120, verbose_name='Время работы')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Станция метро')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('lounge_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lounge.lounge', verbose_name='Lounge ID')),
            ],
        ),
        migrations.CreateModel(
            name='LoungePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lounge.lounge', verbose_name='Lounge')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='Фото')),
            ],
        ),
        migrations.AddField(
            model_name='lounge',
            name='metro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lounge.metro', verbose_name='Метро'),
        ),
    ]
