# Generated by Django 5.0.6 on 2024-06-10 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tobacco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название микса')),
                ('desc', models.TextField(verbose_name='Описание')),
                ('category_id', models.IntegerField(verbose_name='ID категории')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название тэга')),
            ],
            options={
                'verbose_name': 'Тэг',
                'verbose_name_plural': 'Тэги',
            },
        ),
        migrations.CreateModel(
            name='Variants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название варианта')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты',
            },
        ),
        migrations.CreateModel(
            name='MixPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(verbose_name='Процент')),
                ('mix_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mix.mix', verbose_name='ID микса')),
                ('tobacco_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tobacco.product', verbose_name='ID табака')),
            ],
        ),
        migrations.AddField(
            model_name='mix',
            name='tag',
            field=models.ManyToManyField(to='mix.tag'),
        ),
        migrations.AddField(
            model_name='mix',
            name='variants',
            field=models.ManyToManyField(to='mix.variants'),
        ),
    ]
